### PR TITLE
Fitness bugs

### LINKED ISSUE #103: FE: Piggy bank changed back to zero

### LINKED ISSUE #105: FE: Fitness max doesn't should "All money earned, nice!" properly

### PR DESCRIPTION
**Pull request by laurawyse**
## Description
* Allow re-saving a fitness activity for today when using a piggy bank
* Display the "max" message for fitness in the dashboard when you score 8 points

## Issues
* Closes #105 
* Closes #103

### CODE REVIEW

File: app/models/user.rb [hunk 1]
```diff
@@ -24,4 +23,8 @@ class User < ApplicationRecord
   def points
     UserPoints.total_for_user(self) + UserStreakPoints.total_for_user(self)
   end
+
+  def used_piggy_bank_today
+    !UserPiggyBanks.find_by(is_used: true, date_used: DateUtil.current_date).nil?
```
Comment (jjwyse) [inline app/models/user.rb]: Can also use `.present?` to avoid the double neg
